name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check PR title
        uses: open-edge-platform/geti-ci/actions/conventional-pr-title@0bed754fc7db24b5f9f15e7ead2eb4acdb0c7263 # v0.1.2
