name: Renovate

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  renovate:
    name: Renovate dependency updates
    runs-on: ubuntu-latest
    environment: renovate # dedicated environment for RENOVATE_TOKEN
    permissions:
      contents: read # to check out code
      pull-requests: write # to create update PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Renovate
        uses: renovatebot/github-action@481e9bc4c7b2c120a2cbb3c40053adf4230bd86f # v42.0.1
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
