name: Renovate Config Validator

on:
  pull_request:
    paths:
      - ".github/renovate.json5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    name: Validate renovate config
    runs-on: ubuntu-latest
    permissions:
      contents: read # to check out code
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Validate renovate config
        uses: suzuki-shunsuke/github-action-renovate-config-validator@fe49edf1f9911c4b1dcef60f1c2ede8cde414d6b # v2.0.0
        with:
          config_file_path: .github/renovate.json5
