name: Renovate

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  renovate:
    name: Renovate dependency updates
    runs-on: ubuntu-latest
    environment: renovate # dedicated environment for RENOVATE_TOKEN
    permissions:
      contents: read # to check out code
      pull-requests: write # to create update PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Renovate
        uses: renovatebot/github-action@e854b273e774bce1ef8cb05f128b8ce8aee2a887 # v42.0.1
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
