name: Renovate

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Renovate
        uses: renovatebot/github-action@481e9bc4c7b2c120a2cbb3c40053adf4230bd86f # v42.0.1
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
